# 1. 开启鼠标支持 (极其推荐)
set -g mouse on

# 2. 修改前缀键为 Ctrl+a (更方便)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# 3. 优化分屏快捷键为 | (左右) 和 - (上下)
unbind '"'
bind - split-window -v
unbind %
bind | split-window -h

# pane 切换（vim 风格）
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 4. 支持 vim 模式操作
setw -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection
